## Numpy array and basics

In [3]:
import numpy as np

### creating array from list

In [6]:
arr_1D= np.array([1,2,3,4,5])
print("1D array",arr_1D)

arr_2D=np.array([[1,2,3],[5,6,7]])
print("2D array",arr_2D)

1D array [1 2 3 4 5]
2D array [[1 2 3]
 [5 6 7]]


## List vs numpy

In [8]:
py_list=[1,2,3]
print("list multiplication",py_list*3)

np_array=np.array([1,2,3]) # element wise multiplication
print("array multiplication",np_array*3)

list multiplication [1, 2, 3, 1, 2, 3, 1, 2, 3]
array multiplication [3 6 9]


In [9]:
import time
start =time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ",time.time()-start)

start =time.time()
np_array=np.arange(1000000)*2
print("\n Numpy operation time: ",time.time()-start)


 List operation time:  0.10709857940673828

 Numpy operation time:  0.009641647338867188


## creating array from scratch

In [11]:
zeros=np.zeros((3,4))
print("zeros array:\n,",zeros)

ones=np.ones((3,4))
print("zeros array:\n,",ones)

full=np.full((2,2),7)
print("full array:\n,",full)


zeros array:
, [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
zeros array:
, [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array:
, [[7 7]
 [7 7]]


In [13]:
random=np.random.random((2,3))
random

array([[0.13761525, 0.36266168, 0.21403498],
       [0.72442294, 0.41068402, 0.99709492]])

In [15]:
sequence=np.arange(0,10,2)
sequence

array([0, 2, 4, 6, 8])

## Vector, Matrix and Tensor

In [17]:
vector=np.array([1,2,3])
print("vector: ",vector)

matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("vector: ",matrix)

tensor=np.array([[[1,2,3],[4,5,6]]
                 ,[[3,4,5],[6,7,8]]])
print("tensor: ",tensor)

vector:  [1 2 3]
vector:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor:  [[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [6 7 8]]]


### Array properties

In [19]:
arr= np.array([[1,2,3],
               [4,5,6]])
print("Shape ",arr.shape)
print("Dimension ",arr.size)
print("Dtype ",arr.dtype)

Shape  (2, 3)
Dimension  6
Dtype  int64


### Array reshaping

In [24]:
arr=np.arange(12)
print("Original array: ",arr)

reshaped=arr.reshape((3,4))
print("Reshaped array: ",reshaped)

flattened=reshaped.flatten()
print("flattened array: ",flattened)

# revel (returns view, instead of copy)
reveled =reshaped.ravel()
print("reveled array: ",reveled)

# Transpose
transpose=reshaped.T
print("Transposed array: ",transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
