## Numpy Array operations

In [2]:
import numpy as np

In [7]:
array=np.arange(10)
print("Basic Slicing",array[2:5])
print("With Step",array[1:8:2])
print("Negative indexing",array[-2])

Basic Slicing [2 3 4]
With Step [1 3 5 7]
Negative indexing 8


In [10]:
array_2D=np.array([[1,2,3],
                   [7,8,9],
                   [4,5,6]])
print("Specific element",array_2D[1,2])
print("Entire row",array_2D[1])
print("Entire column",array_2D[:,1])


Specific element 9
Entire row [7 8 9]
Entire column [2 8 5]


## Sorting

In [15]:
unsorted=np.array([3,7,8,1,0,33,22,23])
print("Sorted array",np.sort(unsorted))

array_2D_unsorted=np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column",np.sort(array_2D_unsorted,axis=0))

Sorted array [ 0  1  3  7  8 22 23 33]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


## Filter

In [16]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers%2==0]
print(even_number)

[ 2  4  6  8 10]


# Filter with mask

In [20]:
mask=numbers > 5
print("numbers greater than 5 ",numbers[mask])

numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [24]:
indices=[0,2,5]
print(numbers[indices])

where_result=np.where(numbers>6)
print("NP where",numbers[where_result])

[1 3 6]
NP where [ 7  8  9 10]


In [34]:
condition_array=np.where(numbers>5,numbers*4,numbers)
print(condition_array)


[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [39]:
arr1=np.array([2,3,4,5,6,8])
arr2=np.array([8,9,22,33,55,88])

combinedArray=np.concatenate((arr1,arr2))
print(combinedArray)

[ 2  3  4  5  6  8  8  9 22 33 55 88]


### Array compatibility

In [4]:
a=np.array([2,3,4,5,6,8])
b=np.array([8,9,22,33,55])
c=np.array([1,2,3,4,5,6])

print("Compatibility",a.shape==c.shape)

Compatibility True


In [9]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original,new_row))  ### new adds row 
print(original)
print("with new row: ",with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print(original)
print("with new col: ",with_new_col)

[[1 2]
 [3 4]]
with new row:  [[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
with new col:  [[1 2 7]
 [3 4 8]]


In [11]:
arr=np.array([1,2,3,4,5,8])
deleted=np.delete(arr,2)

print("Array after deletion: ",deleted)

Array after deletion:  [1 2 4 5 8]
